/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 .\public\models\scene.glb -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-0.235, 0.242, -0.738]} rotation={[-Math.PI, 0.335, -Math.PI]}>
          <group name="Armature">
            <primitive object={nodes.Hips} />
          </group>
          <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials['Wolf3D_Body.001']} skeleton={nodes.Wolf3D_Body.skeleton} />
          <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials['Wolf3D_Hair.001']} skeleton={nodes.Wolf3D_Hair.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials['Wolf3D_Outfit_Footwear.001']} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials['Wolf3D_Outfit_Top.001']} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
          <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.001']} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
          <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.001']} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials['Wolf3D_Skin.001']} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials['Wolf3D_Teeth.001']} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
        </group>
        <group name="Plane">
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Material} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials.Glass} />
          <mesh name="Plane001_2" geometry={nodes.Plane001_2.geometry} material={materials.walls_wh} />
          <mesh name="Plane001_3" geometry={nodes.Plane001_3.geometry} material={materials.wood} />
        </group>
        <group name="mew" position={[-0.532, 2.176, -2.006]} rotation={[-Math.PI, 0.277, -Math.PI]}>
          <mesh name="mesh731660817" geometry={nodes.mesh731660817.geometry} material={materials.mat6} />
          <mesh name="mesh731660817_1" geometry={nodes.mesh731660817_1.geometry} material={materials.mat21} />
          <mesh name="mesh731660817_2" geometry={nodes.mesh731660817_2.geometry} material={materials.mat5} />
          <mesh name="mesh731660817_3" geometry={nodes.mesh731660817_3.geometry} material={materials['mat23.002']} />
        </group>
        <group name="plant_left" position={[-2.019, -0.042, -1.526]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh name="Houseplant_7" geometry={nodes.Houseplant_7.geometry} material={materials['Black.001']} />
          <mesh name="Houseplant_7_1" geometry={nodes.Houseplant_7_1.geometry} material={materials['Brown.001']} />
          <mesh name="Houseplant_7_2" geometry={nodes.Houseplant_7_2.geometry} material={materials['Plant_Green.001']} />
        </group>
        <group name="monitor" position={[0.083, 0.939, -1.723]} rotation={[Math.PI, -1.366, Math.PI]}>
          <mesh name="iMac_1" geometry={nodes.iMac_1.geometry} material={materials.ScreenBlack} />
          <mesh name="iMac_1_1" geometry={nodes.iMac_1_1.geometry} material={materials.iMacBody} />
        </group>
        <group name="keyboard" position={[-0.158, 0.981, -1.395]} rotation={[0, -0.165, 0]} scale={0.713}>
          <mesh name="mesh425587018" geometry={nodes.mesh425587018.geometry} material={materials['mat21.004']} />
          <mesh name="mesh425587018_1" geometry={nodes.mesh425587018_1.geometry} material={materials['mat22.001']} />
          <mesh name="mesh425587018_2" geometry={nodes.mesh425587018_2.geometry} material={materials['mat9.002']} />
          <mesh name="mesh425587018_3" geometry={nodes.mesh425587018_3.geometry} material={materials['mat16.001']} />
        </group>
        <group name="lavalamp" position={[-1.302, 2.071, -1.986]}>
          <mesh name="Node-Mesh001" geometry={nodes['Node-Mesh001'].geometry} material={materials.lambert4SG} />
          <mesh name="Node-Mesh001_1" geometry={nodes['Node-Mesh001_1'].geometry} material={materials['lambert2SG.001']} />
          <mesh name="Node-Mesh001_2" geometry={nodes['Node-Mesh001_2'].geometry} material={materials['lambert3SG.002']} />
        </group>
        <group name="palm_tree_01" position={[2.166, 0, -0.981]} rotation={[-Math.PI, 0.844, -Math.PI]}>
          <mesh name="palm_tree_01-Mesh001" geometry={nodes['palm_tree_01-Mesh001'].geometry} material={materials['795548']} />
          <mesh name="palm_tree_01-Mesh001_1" geometry={nodes['palm_tree_01-Mesh001_1'].geometry} material={materials['8BC34A']} />
          <mesh name="palm_tree_01-Mesh001_2" geometry={nodes['palm_tree_01-Mesh001_2'].geometry} material={materials.DD9944} />
        </group>
        <mesh name="mouse" geometry={nodes.mouse.geometry} material={materials.ComputerMouse_mat1} position={[0.239, 0.95, -1.306]} rotation={[-Math.PI, 0.345, -Math.PI]} />
        <group name="shelf" position={[-0.868, 1.694, -2.038]}>
          <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={materials.lambert2SG} />
          <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={materials['795548.001']} />
        </group>
        <group name="speaker_right" position={[0.607, 0.936, -1.605]} rotation={[0, -0.324, 0]}>
          <mesh name="speaker003" geometry={nodes.speaker003.geometry} material={materials['Black.005']} />
          <mesh name="speaker003_1" geometry={nodes.speaker003_1.geometry} material={materials['LightGrey.004']} />
        </group>
        <group name="speaker_left" position={[-0.389, 0.934, -1.76]} rotation={[0, 0.126, 0]}>
          <mesh name="speaker002" geometry={nodes.speaker002.geometry} material={materials['Black.004']} />
          <mesh name="speaker002_1" geometry={nodes.speaker002_1.geometry} material={materials['LightGrey.003']} />
        </group>
        <group name="Desk" position={[-0.074, 0, -1.521]} rotation={[0, -Math.PI / 2, 0]}>
          <mesh name="Plane001_Plane002_BlackWood001" geometry={nodes.Plane001_Plane002_BlackWood001.geometry} material={materials['BlackWood.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_1" geometry={nodes.Plane001_Plane002_BlackWood001_1.geometry} material={materials['BlackCoatSteel.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_2" geometry={nodes.Plane001_Plane002_BlackWood001_2.geometry} material={materials['GrayPlastic.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_3" geometry={nodes.Plane001_Plane002_BlackWood001_3.geometry} material={materials['WhiteSteelScrew.001']} />
          <mesh name="Plane001_Plane002_BlackWood001_4" geometry={nodes.Plane001_Plane002_BlackWood001_4.geometry} material={materials['BlackPlastic.001']} />
        </group>
        <mesh name="WawaRug" geometry={nodes.WawaRug.geometry} material={materials.Rug} position={[-0.281, 0.009, 0.765]} />
        <mesh name="screen" geometry={nodes.screen.geometry} material={materials.Screen} position={[0.083, 0.939, -1.723]} rotation={[Math.PI, -1.366, Math.PI]} />
        <group name="Desk_Chair" position={[-0.193, 0, -0.782]} rotation={[0, -0.363, 0]} scale={126.038}>
          <mesh name="Desk_Chair_1" geometry={nodes.Desk_Chair_1.geometry} material={materials.mat23} />
          <mesh name="Desk_Chair_2" geometry={nodes.Desk_Chair_2.geometry} material={materials.mat16} />
          <mesh name="Desk_Chair_3" geometry={nodes.Desk_Chair_3.geometry} material={materials.mat20} />
          <mesh name="Desk_Chair_4" geometry={nodes.Desk_Chair_4.geometry} material={materials.mat17} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
